### ISSUE TITLE
Error: Folder does not exist error: recon-all-t1.sh

### ISSUE THREAD

**Issue by teffalump** [beauchamplab/raveio#19]
When I try to run the recon-all-t1.sh shell script it has an error for the line below as that folder that does not exist. I believe I have tracked it to these lines

At the end of the shell script

https://github.com/beauchamplab/raveio/blob/e3c52d674683e80d230e64c5557ef0c080f70b9d/inst/shell-templates/recon-all-t1.sh#L126-L130

SUBJECTS_DIR is 

https://github.com/beauchamplab/raveio/blob/e3c52d674683e80d230e64c5557ef0c080f70b9d/inst/shell-templates/recon-all-t1.sh#L95

`wdir_fs` is in the .cache path, on my computer is expanded to `~/.cache/R/raveio/FreeSurfer/<subject id>` and it is deleted by the `rm` command preceding `cp` and consequently `SUBJECTS_DIR` (`~/.cache/R/raveio/FreeSurfer/<subject id>/rave-imaging`) does not exist which caused the `No such file or directory`

I believe `SUBJECTS_DIR` should be exchanged for `$wdir_actual/rave-imaging` or equivalent, similar to: https://github.com/beauchamplab/raveio/blob/e3c52d674683e80d230e64c5557ef0c080f70b9d/inst/shell-templates/yael-preprocess.sh#L159

**Comment by dipterix** [comment]
Yes, this is a typo+bug that existed for a while. Basically RAVE uses the `brain.finalsurfs.mgz` as underlay by default. RAVE allows you to set custom underlay by putting `rave_slices.???` under the `mri` folder, provided that this file sits under the same coordinates as the T1 image.

I was trying to copy the raw T1 here and name it `rave_slices`. This operation is optional (part of reasons why I didn't fix it). Also, the T1 images are sometime too dark, or the contrast is too low. I'm currently working on the 3D viewer so you can adjust the brightness and contrast on the fly. Also I have recently release a new pipeline (with non-linear normalization to template MNI152) that does the brain masking and intensity correction without FreeSurfer.

Maybe it would be a good chance for me to come back and fix this after the dynamical contrast & brightness adjustment. Please let me know if this is urgent to you and I can prioritize.

**Comment by dipterix** [comment]
Also we have a slack channel for RAVE and YAEL for more interactive Q&A. Please let me know if you would like to join or send your edu email to _slack_ at _rave.wiki_. Thanks for reporting this issue : )

**Comment by dipterix** [comment]
I fixed this problem. Could you update RAVE and retry? @teffalump

**Comment by teffalump** [comment]
Hi, sorry for delay. I'll try the updated code soon.

**Comment by dipterix** [comment]
Not a hurry at all. Thanks for posting this issue : )

**Comment by teffalump** [comment]
Just ran it on a new sEEG patient and works. Thanks.
